### PR TITLE
Support React 17

### PR DESCRIPTION
**Pull request by chris-erickson**
Seems to work just fine with React 17, and would help with this:
```
❯ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @mysite/site@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0" from react-twitter-embed@3.0.3
npm ERR! node_modules/react-twitter-embed
npm ERR!   react-twitter-embed@"3.0.3" from the root project
```

### CODE REVIEW

**Comment by saurabhnemade** [comment]
@chris-erickson 
Looks good. 
Can we keep all `^15.0.0 || ^16.0.0 || ^17.0.0` ?

Don't want folks using 16 missing out on it. :) 

Anyway I'll be doing rewrite of whole thing soon enough (once I get little bit of free from working for 3 clients everyday) to move to hooks and typescript for resolution of many opened issus. Till then I suppose we can go with your suggested fix with inclusion of all react & react-dom versions. :)

**Comment by chris-erickson** [comment]
Yes absolutely I just goofed on that.  Glad to hear there's updates in the pipeline too!

**Comment by chris-erickson** [comment]
@saurabhnemade I made the update, should be set.

**Review by idreamer — APPROVED** [review]

**Comment by saurabhnemade** [comment]
this will be taken care with https://github.com/saurabhnemade/react-twitter-embed/pull/89.

**Comment by saurabhnemade** [comment]
this has been taken care in rewrite.

**Pull request closed without merging**
