### PR TITLE
Rewrite with typescript

### PR DESCRIPTION
**Pull request by saurabhnemade**
- Upgrading the boilerplate.
- Upgrading storybook making story writing a little simple.
- Much asked Typescript :tada: the right way. Could be even better which will be added in future.
- Github worflow added and starting to move away from travis ci.

### CODE REVIEW

**Comment by saurabhnemade** [comment]
Just an update:
We now have cypress. 🚀 

https://user-images.githubusercontent.com/17445338/131757071-abd3a25c-735f-4309-ba4b-e9f0c51fe807.mp4

**Comment by saurabhnemade** [comment]
Screenshot 2021-09-02 at 5 51 35 AM

**Comment by maccman** [comment]
Excited for this.

**Comment by bcerati** [comment]
Any news when this will be released?

**Comment by saurabhnemade** [comment]
> Any news when this will be released?

It will be published by next week. I am trying to get some final stuff reviewed and removing all the junk. this is mostly confirmed but want to make it solid before I hit that publish step. :)

**Comment by dylanjeffers** [comment]
Looking forward!

**Comment by dane-brown** [comment]
Just wanted to follow up and see if we are close to getting this released?

**Comment by saurabhnemade** [comment]
> Just wanted to follow up and see if we are close to getting this released?

Timeline is important feature and I noticed a lot of users are using it. Unfortunately its broken recently despite of previously working tests. So trying out possible options to fix it so it will be seamless experience.

**Comment by johannesnagl** [comment]
Wow, so cool! Thanks!

**Pull request merged**
